services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: language-cards-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - language-cards-network
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:alpine
    container_name: language-cards-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - language-cards-network

  db:
    image: mysql:8.0
    container_name: language-cards-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: language_cards_shop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - language-cards-network

  redis:
    image: redis:alpine
    container_name: language-cards-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - language-cards-network

volumes:
  dbdata:

networks:
  language-cards-network:
    driver: bridge